<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="assets/css/custom.css" />
        <link rel="stylesheet" href="assets/css/navbar.css" />
    </head>
    <body>
        <header class="home">
            <div class="logo">
                <img src="assets/img/logo.svg" alt="logo ok" />
            </div>
            <div class="nav">
                <input type="checkbox" id="nav-check" />           
                <div class="nav-btn">
                    <label for="nav-check">
                        <span></span>
                        <span></span>
                        <span></span>
                    </label>
                </div>
    
                <div class="nav-links">
                    <a href="index.phtml">Home</a>
                    <a href="blog.phtml">Blog</a>
                    <a href="post.phtml">Services</a>
                    <a href="sobre.phtml">About</a>
                    <a href="contato.phtml">Contact</a>
                </div>
            </div>           
        </header>
        <div class="container">
            <section class="flexNews">
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/5/480/260" />
                    </picture>
                    <h2>Nullam placerat lobortis mi vitae</h2>
                    <p>Fusce eget felis et dolor ultricies convallis non sollicitudin dolor. Duis pharetra bibendum lorem at dapibus. Praesent accumsan libero non est faucibus, sed egestas risus suscipit.</p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/10/480/260" />
                    </picture>
                    <h2>Nullam placerat lobortis mi vitae</h2>
                    <p>Fusce eget felis et dolor ultricies convallis non sollicitudin dolor. Praesent accumsan libero non est faucibus, sed egestas risus suscipit.</p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/15/480/260" />
                    </picture>
                    <h2>Nullam placerat lobortis mi vitae</h2>
                    <p>Fusce eget felis et dolor ultricies convallis non sollicitudin dolor. Duis pharetra bibendum lorem at dapibus. Praesent accumsan libero non est faucibus, sed egestas risus suscipit.</p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/20/480/260" />
                    </picture>
                    <p>Consequuntur rerum dolorem 4   </p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/25/480/260" />
                    </picture>
                    <p>Dolor quibusdam tempora libero 5</p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/30/480/260" />
                    </picture>
                    <p>Odio pariatur aliquid vel 6</p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/35/480/260" />
                    </picture>
                    <p>Ab repellendus quisquam 7</p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/40/480/260" />
                    </picture>
                    <p>Alias corrupti sit 8 </p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/45/480/260" />
                    </picture>
                    <p>Corporis officiis? 9 </p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/50/480/260" />
                    </picture>
                    <p>Legenda 10 </p>
                </div>
                <div>
                    <picture>
                        <img src="https://picsum.photos/id/55/480/260" />
                    </picture>
                    <p>Legenda 11</p>
                </div>                
                <div class="anuncio">
                    <picture>
                        <img src="https://picsum.photos/id/75/1260/850" />
                    </picture>
                    <p>Quibusdam quis in architecto quidem. Iure, dolor quibusdam?</p>
                </div>
            </section>          
        </div>
        <footer>
            <p>
                by Rogério Soares - 2021 &copy Direitos reservados
            </p>
        </footer>
    </body>
</html>
